source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, ‘8.1’
use_frameworks!

target:RxTableViewDemo do
      pod 'RxSwift', '~> 3.1'
      pod 'RxCocoa', '~> 3.1'
      pod 'RxDataSources', '~> 1.0.0’
end


